- Assets/Plugins/Decrepit Dungeon LITE/Prefabs/Floors/Floor_A.prefab
- Assets/Plugins/Decrepit Dungeon LITE/Prefabs/Pillars/4x4Room_A.prefab
- Assets/Plugins/Decrepit Dungeon LITE/Prefabs/Pillars/4x4Room_A.prefab.meta
- Assets/Resources/Materials.meta
- Assets/Resources/Materials/tempEscapeItem.mat
- Assets/Resources/Materials/tempEscapeItem.mat.meta
- Assets/Resources/Materials/tempEscapePoint.mat
- Assets/Resources/Materials/tempEscapePoint.mat.meta
- Assets/Resources/Prefab/Stage/1x1x2Room_B.prefab
- Assets/Resources/Prefab/Stage/1x1x2Room_B.prefab.meta
- Assets/Resources/Prefab/Stage/1x3Room_A.prefab
- Assets/Resources/Prefab/Stage/1x3Room_A.prefab.meta
- Assets/Resources/Prefab/Stage/2x2Room_B.prefab
- Assets/Resources/Prefab/Stage/2x2Room_B.prefab.meta
- Assets/Resources/Prefab/Stage/2x3Room_A.prefab
- Assets/Resources/Prefab/Stage/2x3Room_A.prefab.meta
- Assets/Resources/Prefab/Stage/2x3Room_B.prefab
- Assets/Resources/Prefab/Stage/2x3Room_B.prefab.meta
- Assets/Resources/Prefab/Stage/3x3Room_A.prefab
- Assets/Resources/Prefab/Stage/3x3Room_A.prefab.meta
- Assets/Resources/Prefab/Stage/SpawnRoom.prefab
- Assets/Resources/Prefab/Stage/SpawnRoom.prefab.meta
- Assets/Scenes/InGame.unity
仮置きの脱出アイテムと脱出地点の追加
- [] 命名規則の統一
> 仮置き用の脱出地点、脱出アイテムの追加。ステージの修正

- Assets/Scenes/InGame_Player.unity
- Assets/Scenes/InGame_Player.unity.meta
- Assets/Scripts/Scenes/InGame/Player/DisplayPlayerStatusManager.cs
- Assets/Scripts/Scenes/InGame/Player/DisplayPlayerStatusManager.cs.meta
- Assets/Scripts/Scenes/InGame/Player/Enums.meta
- Assets/Scripts/Scenes/InGame/Player/Enums/PlayerActionEnums.cs
- Assets/Scripts/Scenes/InGame/Player/Enums/PlayerActionEnums.cs.meta
- Assets/Scripts/Scenes/InGame/Player/Interface.meta
- Assets/Scripts/Scenes/InGame/Player/PlayerGUIPresenter.cs
- Assets/Scripts/Scenes/InGame/Player/PlayerGUIPresenter.cs.meta
- Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
- Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs.meta
プレイヤーのステータス関係の仮実装
- 体力,スタミナ,SAN値の実装
- 出血状態の仮実装
- [] 命名規則の統一
> プレイヤーのステータス関係の仮実装

- Assets/Scripts/Scenes/InGame/Manager/IngameManager.cs
- Assets/Scripts/Scenes/InGame/Manager/IngameReady.cs
- Assets/Scripts/Scenes/InGame/Manager/ReadyEnum.cs
- Assets/Scripts/Scenes/InGame/Manager/ReadyEnum.cs.meta
IngameManagerに脱出アイテムと脱出地点に関する処理の追加。SetReadyの引数の変更
- IngameManagerに生成する脱出アイテム数の関数の追加
- IngameManagerに脱出アイテムを取得した際の処理の追加
- SetReadyの引数をboolからenumに変更
> IngameManageの修正

- Assets/Resources/Materials/tempEscapePointNegative.mat
- Assets/Resources/Materials/tempEscapePointNegative.mat.meta
- Assets/Resources/Prefab/Stage/escapeItem.prefab
- Assets/Resources/Prefab/Stage/escapeItem.prefab.meta
- Assets/Resources/Prefab/Stage/escapePoint.prefab
- Assets/Resources/Prefab/Stage/escapePoint.prefab.meta
- Assets/Scenes/InGame_Manager.unity
- Assets/Scripts/Scenes/InGame/Manager/EscapeItem.cs
- Assets/Scripts/Scenes/InGame/Manager/EscapeItem.cs.meta
- Assets/Scripts/Scenes/InGame/Manager/EscapePoint.cs
- Assets/Scripts/Scenes/InGame/Manager/EscapePoint.cs.meta
- Assets/Scripts/Scenes/InGame/Manager/IngameManager.cs
脱出アイテムと脱出ポイントの機能追加
- 脱出ポイントの機能追加
- 脱出アイテムの機能追加
- 変化が分かりやすいようにマテリアルの追加
- プレファブの修正
- [] 命名規則の統一
> 脱出アイテムと脱出ポイントの機能追加

- Assets/Resources/Prefab/Stage/NewStages/TEST.meta
- Assets/Resources/Prefab/Stage/NewStages/TEST/2x2RoomTEST.prefab
- Assets/Resources/Prefab/Stage/NewStages/TEST/2x2RoomTEST.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/TEST/2x3RoomTEST.prefab
- Assets/Resources/Prefab/Stage/NewStages/TEST/2x3RoomTEST.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/TEST/3x2RoomTEST.prefab
- Assets/Resources/Prefab/Stage/NewStages/TEST/3x2RoomTEST.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/TEST/3x3RoomTEST.prefab
- Assets/Resources/Prefab/Stage/NewStages/TEST/3x3RoomTEST.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/TEST/3x4RoomTEST.prefab
- Assets/Resources/Prefab/Stage/NewStages/TEST/3x4RoomTEST.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/TEST/4x3RoomTEST.prefab
- Assets/Resources/Prefab/Stage/NewStages/TEST/4x3RoomTEST.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/TEST/4x4RoomTEST.prefab
- Assets/Resources/Prefab/Stage/NewStages/TEST/4x4RoomTEST.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/TEST/SpawnRoomTEST.prefab
- Assets/Resources/Prefab/Stage/NewStages/TEST/SpawnRoomTEST.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/WallXDoor.prefab
- Assets/Resources/Prefab/Stage/NewStages/WallXDoor.prefab.meta
- Assets/Resources/Prefab/Stage/NewStages/WallYDoor.prefab
- Assets/Resources/Prefab/Stage/NewStages/WallYDoor.prefab.meta
- Assets/Scenes/InGame_Stage.unity
- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
今まで部屋の壁同士が重なっていた部分を、削除しスクリプトからない部分の壁を補うように機能を変更
- テスト用の部屋、壁のぷれふぁぶの追加
- 壁を動的に割り当てる機能の実装
- 通路生成時のデータ内の配列がずれる問題を修正 
- [] 命名規則の統一
- 現在部屋のプレファブの都合で壁同士に隙間が空いている場所があります、それは部屋のプレファブを修正したら直る予定なので、いったん気にしないでください。
> ステージ生成の処理変更

- Assets/Resources/Prefab/Stage.prefab
- Assets/Resources/Prefab/Stage.prefab.meta
- Assets/Scenes/InGame_Stage.unity
- Assets/Scripts/Scenes/InGame/Stage/RoomType.cs
- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
処理速度を上げるためUniTaskに変更いたしました。
IngameManagerへステージ生成完了を通知するようにしました。
- VoidをUniTaskに変更
- Stage生成オブジェクトをprefab化
- ステージ生成完了を通知する機能実装
- 同一処理のリファクタリング
> UniTaskへの移行、IngameManagerへのステージ生成完了を通知

- Assets/Scenes/InGame.unity
- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
インゲームに置かれているステージ生成のオブジェクトをリソースに置かれているものに置き換える
- Ingameのオブジェクトの置き換え
- エラーが発生したスクリプトの修正
- [] 命名規則の統一
> インゲームにステージ生成のプレファイブをアタッチ

- Assets/Resources/Prefab/Stage.prefab
- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
ステージ上に屋根を張るように機能追加
- ステージに屋根を張る機能の追加
> ステージに屋根を張る機能の追加

- Assets/Resources/Prefab/Manager.prefab
- Assets/Resources/Prefab/ResultCanvas.prefab
- Assets/Scenes/InGame_Stage.unity
- Assets/Scripts/Scenes/InGame/Manager/ResultManager.cs
- Assets/Scripts/Scenes/InGame/Manager/ResultManager.cs.meta
- Assets/Scripts/Scenes/InGame/System/ResultValue.cs
- Assets/Scripts/Scenes/InGame/System/ResultValue.cs.meta
- Assets/Scripts/Scenes/InGame/System/UI/ResultPresenter.cs
ゲームクリア時に報酬画面を表示する機能の実装
- ResultCanvasの追加
- ゲームクリア時に報酬画面を出す機能の追加 
- [] 命名規則の統一
テストはIngame_Stageで行ってください。
テスト方法は、おいてある脱出アイテム（緑）を拾って脱出ポイント（青）に行ってください
現在結果は仮置きのものです
> 脱出時の報酬画面機能の実装

- Assets/Scenes/Player_Spawn.unity
- Assets/Scenes/Player_Spawn.unity.meta
> PlayerをSpawnroomにスポーンさせる

- Assets/Plugins/Horror_House/Prefabs/House/Wall/Interior_Door_01.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Bone_04.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Candle_01.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Candle_02.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Candle_03.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Candle_04.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Ficus.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Fireplace_Set.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Home_Flower_01.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Home_Flower_02.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Mannequin_01.prefab
- Assets/Plugins/Horror_House/Prefabs/Props/Skull.prefab
- Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
- Assets/Scripts/Scenes/InGame/Stage/StageDoor.cs
- Assets/Scripts/Scenes/InGame/Stage/StageDoor.cs.meta
ドアの開閉機能の追加
一部オブジェクトをNavmeshのbake対象外に設定
- ドアをインタラクトで開閉する機能の実装
- ステージの小物をNavmeshのbake対象外に設定
> ステージのオブジェクトのNavMeshの最適化とドアの開閉機能の実装

- Assets/Resources/Prefab/Player.prefab
- Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
スタミナ消費後にスタミナが速く回復する機能追加
編集していたスクリプトが更新されていたため、新たにブランチを作りました。
変更点１文字コードをShift JISに変更
変更点２スタミナが完全回復するまで走行不可になるよう修正
> スタミナ消費後の急速回復

- .github/workflows/auto-review-assign.yml
レビュアーを自動でセットしてくれる機能の導入のテスト
レビュアーを自動でセットしてくれる機能の導入
- レビュアーを自動でセットしてくれる機能の導入
- [] 命名規則の統一
> レビュアーを自動でセットしてくれる機能の導入[お試し]

- README.md
READMEにQuickOutlineの追加
- READMEにQuickOutlineの追加
- [] 命名規則の統一
> READMEにQuickOutlineの追加

- Assets/Resources/Prefab/Player.prefab
- Assets/Scenes/InGame_Player.unity
PrefabにMagicスクリプトが無かったのを修正
動作確認用シーン：Ingame_Player
> PrefabにMagicスクリプトが無かったのを修正

- Assets/Scripts/Scenes/InGame/Enemy/EnemyVisibilityMap.cs
- プレイヤーと敵の座標がスキャンしている範囲内にいるかどうかを正常に検出できるようにした。
> 敵キャラクターのマップスキャンにおいて、範囲外の判定が適切にできていなかったのを修正

- Assets/Plugins/Horror_House/Prefabs/Furniture/Wardrobe_03.prefab
- Assets/Plugins/Horror_House/Prefabs/House/Floor_2x2m_02.prefab
- Assets/Plugins/Horror_House/Prefabs/House/Wall/Interior_Door_01.prefab
- Assets/Resources/Prefab/Player.prefab
- Assets/Resources/Prefab/PlayerUI.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/Floor_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/InSideWallX_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/InSideWallY_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/OutSideWallX_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/OutSideWallY_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/WallXDoor_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/WallYDoor_HH.prefab
- Assets/Scenes/InGame_Player.unity
- Assets/Scenes/InGame_Player.unity.meta
- Assets/Scripts/Scenes/InGame/Player/Item/Interface/IInteractable.cs
- Assets/Scripts/Scenes/InGame/Player/Item/ItemInstract.cs
- Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
- Assets/Scripts/Scenes/InGame/Player/Magic/MagicScripts/CreateBarricadeMagic.cs
- Assets/Scripts/Scenes/InGame/Player/PlayerGUIPresenter.cs
- Assets/Scripts/Scenes/InGame/Stage/StageDoor.cs
- Assets/Scripts/Scenes/InGame/System/EscapeItem.cs
- ProjectSettings/TagManager.asset
アイテムのアウトラインの機能修正
アイテム取得の利便性をアップ
- 以前出したプルリクの一部の変更が消えていたので再度設定（Layer,スクリプトなど）
- 壁越しでのアイテム取得を防止
- ドアの開閉状態に応じてポップの文字を変化
- アイテムを取得時、自動的に空きスロットに割り当てる（選択中のアイテムスロット優先）
動作確認用シーン：Ingame_Player
> アイテムのアウトラインの機能修正 & アイテム取得の利便性をアップ

- Assets/Plugins/Adventure_Character/Animation/Player.controller
- Assets/Resources/Prefab/Player.prefab
- Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
- Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
アニメーション遷移用のfloat型変数をスクリプトで変更
- アニメーション遷移用のfloat型変数にCharacterControllerのVelocityの値を代入させるようにした。
動作確認用シーン：Ingame_Player
> アニメーションの設定変更

- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
ステージ端に壁に埋まったドアが生成され、開けれるのを修正
壁の生成位置を内側に寄せることで、触れないようにした。
- 端の壁の位置の修正
動作確認用シーン：
- [] 命名規則の統一
> ステージ端に壁に埋まったドアが生成され、開けれるのを修正

- Assets/Resources/Prefab/Manager.prefab
- Assets/Scripts/Scenes/InGame/Manager/EventManager.cs
- Assets/Scripts/Scenes/InGame/Manager/EventManager.cs.meta
- Assets/Scripts/Scenes/InGame/Manager/ResultManager.cs
- Assets/Scripts/Scenes/InGame/System/UI/ResultPresenter.cs
実績、呪文の解放条件の確認、報酬に関する情報などを取り扱うイベントマネージャーの作成
- EventManagerの作成
- ResultManagerの一部機能をEventManagerの移動
- ResultPresenterの仮置きのデータを削除
現在の報酬画面に反映されるのは下記の項目です
- 敵との遭遇の有無
- プレイ時間
> イベントを管理するためのマネージャーの作成

- Assets/Scenes/InGame.unity
InGameシーンのステージのスキャンに関係する数値設定を修正。機能追加無し
- InGameシーンのEnemySpawnerのInspecter内部のEnemySpawner.csのステージのスキャンに関係する数値を変更
- [] 命名規則の統一
- 立体に未対応
> InGameシーンでのマップスキャンにかかわる値が不正確であったのを修正

- Assets/Scripts/Scenes/InGame/Manager/EventManager.cs
EventManagerでEnemyStateの名称でエラーが入るバグの修正
動作確認用シーン：
- [] 命名規則の統一
> SafeModeの修正

- Assets/Scripts/Scenes/InGame/Enemy/EnemyVisibilityMap.cs
デバッグログエラーの修正
-DebugLogErrorの位置を修正
- [] 命名規則の統一
> DebugLogErrorの位置が悪く正常に動作しているのにもかかわらずエラーが表示される問題を解決

- Assets/Plugins/Horror_House/HDRP_Horror_House.unitypackage.meta
- Assets/Resources/ItemData/Charm.asset
- Assets/Resources/ItemData/Charm.asset.meta
- Assets/Resources/Prefab/Item/Charm.prefab
- Assets/Resources/Prefab/Item/Charm.prefab.meta
- Assets/Resources/Prefab/Stage/ItemGenerator.prefab
- Assets/Scripts/Scenes/InGame/Manager/EventManager.cs
- Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/CharmEffect.cs
- Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/CharmEffect.cs.meta
- Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
- Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
お守り(サポートアイテム)を実装しました。
効果 : 所持していると常にSAN値減少量が半減する
変更点1 PrefabファイルにCharmオブジェクトを追加
変更点2 PlayerStatusを一部編集
動作確認用シーン：
> お守り(サポートアイテム)実装

- Assets/Scripts/Scenes/InGame/Stage/StageRack.cs
ローカル座標を参照し引き戸を開ける
変更点1:DOMove()をDOLocalMoveに変更
動作確認用シーン：Rack_open
> ローカル座標を参照し引き戸を開ける

- Assets/Scripts/Scenes/InGame/Enemy/EnemyAttack.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyBallet.cs
敵がプレイヤーを攻撃する際にイベントを発行するようになった
- ダメージの判定が出るときにイベントを発行する処理を追加
-テストするシーンのMiGoの判定がおかしいので作成する敵をTestEnemyにしてチェックしてください
> プレイヤーに対して攻撃を行ったときにイベントを発行するようになった

- Assets/Scenes/InGame.unity
InGameSceneのEnemyMakerのInspecter内のyの値を設定した
- InGameSceneのEnemyMakerのInspecter内のyの値を設定した
- [] 命名規則の統一
> InGameのEnemyMakerのインスペクターを設定しました

- Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
- Assets/Scripts/Scenes/InGame/Enemy/UniqueScripts/DeepOnesAction.cs
- Assets/Scripts/Scenes/InGame/Enemy/UniqueScripts/SpawnOfCthulhuAction.cs
Ingameが正常に動作しないエラーの修正
- コンポーネントの参照方法の変更
- インスペクターの数値の調整
- 待機処理の位置修正
- [] 命名規則の統一
> ingameが正常に動作しないerrorの修正

- Assets/Resources/ItemData/AdrenalineSyringe.asset
- Assets/Resources/ItemData/AdrenalineSyringe.asset.meta
- Assets/Resources/Prefab/Item/AdrenalineSyringe.prefab
- Assets/Resources/Prefab/Item/AdrenalineSyringe.prefab.meta
- Assets/Resources/Prefab/Stage/ItemGenerator.prefab
- Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/AdrenalineSyringeEffect.cs
- Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/AdrenalineSyringeEffect.cs.meta
- Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
アドレナリン注射器(スタミナ減少値を半減するサポートアイテム)を再度実装しました。
変更点1 ItemPrefabにAdrenalieSyringeを追加
変更点2 PlayerStatus.csを一部編集
> アドレナリン注射器実装（修正版）

- Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
- Assets/Scripts/Scenes/InGame/Player/PlayerGUIPresenter.cs
「棚・引き出し・ドアのアウトラインが残ってしまう」の修正
https://github.com/InnovaGameCreate/mythos-encounter/issues/106
- アウトラインを表示する処理の修正
> 「棚・引き出し・ドアのアウトラインが残ってしまう」の修正

- Assets/Resources/Prefab/Player.prefab
- Assets/Resources/Prefab/PlayerOld.prefab
- Assets/Scripts/Scenes/InGame/Player/Magic/PlayerMagic.cs
- Assets/Scripts/Scenes/InGame/Player/Map/Map.cs
- Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
- Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
移動関係の修正
アニメーションの修正
- ダッシュ遷移を連続させることでスタミナ消費量を抑えて移動できるグリッチをつぶした
- Shift押してからASDキーを押しても移動しない問題を解決
- 死亡アニメーションが浮く問題を解消, 死亡アニメーションの際アバターが物体にめり込む問題の解消
- 死亡時にアイテム使えないようにした, マップを開けないようにした。
- 死亡アニメーションの際アバターが物体にめり込む問題は解消した。しかし試行回数が少ないので試遊会で試行回数を稼ぎたい。
- InGameSceneにFadeout_InCanvasがない。試遊会までには追加しておきたい（現状InGameシーンいじれないため）
　→ 死亡時のフェードアウトに使う予定
> プレイヤーの移動・アニメーション修正

- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/WallXDoor_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/WallYDoor_HH.prefab
- Assets/Scenes/InGame.unity
- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
ステージサイズを4割に削減、NavMeshの修正
- インスペクターからステージの生成数を調整できるように機能追加
- Ingameのステージの大きさを変更
- NavMeshがつながらない問題の修正
動作確認用シーン：
> 試遊会へ向けたステージの調整

- Assets/Resources/Prefab/FadeOut_InCanvas.prefab
- Assets/Scripts/Scenes/InGame/System/UI/FadeBlackImage.cs
- 死亡時にLayerOrderを変更させるようにした
動作確認用シーン：
- [] 命名規則の統一
> fadeOut用のキャンバス修正

- Assets/Resources/Prefab/Stage.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/4x4Room_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/EscapeRoom_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/EscapeRoom_HH.prefab.meta
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/SpawnRoom_HH 1.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/Wall&Door/SpawnRoom_HH 1.prefab.meta
- Assets/Resources/Prefab/Stage/escapePoint.prefab
- Assets/Scenes/InGame_Stage.unity
- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
- Assets/Scripts/Scenes/InGame/Stage/StagePrefabPool.cs
脱出地点専用の部屋の作成
- 脱出地点のプレファブの大きさを2倍に変更
- 脱出地点専用の部屋を作成
- 4x4Room_HHから脱出地点生成用のマーカーの削除
動作確認用シーン：Ingame_Stage
> 脱出地点専用の部屋の作成

- Assets/Resources/Prefab/MapCanvas.prefab
- Assets/Resources/Prefab/PlayerUI.prefab
- Assets/Resources/Prefab/Stage.prefab
- Assets/Scripts/Scenes/InGame/Player/Map/Map.cs
ミニマップの作成
壁などのMapIconが映らない問題の解消
- ミニマップ作成しました。
- カメラの位置を調整して現在のステージサイズに対応させました。
- rebaseした際に、PlayerUIの_itemEmptySpriteの変更が無くなったとGitHub上ではなっています。実際は変更してない（Unity上で確認済み）のですが、もし消えてたらhotFixで直しておきます
> Map機能の修正・追加

- Assets/Resources/Prefab/Stage/HorrorHouse/2x2Room1_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/2x2Room2_HH.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/2x2Room_Stair1f_TEMP.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/2x2Room_Stair2f_TEMP.prefab
部屋用プレハブに外周用壁プレハブが混入しているのを修正
- ４つのプレハブを編集
> 部屋用プレハブに外周用壁プレハブが混入しているのを修正

- Assets/Resources/Prefab/Enemy/DeepOnes.prefab
- Assets/Resources/Prefab/Enemy/MiGo.prefab
- Assets/Resources/Prefab/Enemy/SpawnOfCthulhu.prefab
- Assets/Resources/Prefab/Enemy/TestEnemy.prefab
- Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
敵キャラクターの抜け落ちていた速度を入力
- 抜け落ちていた敵の速度情報を入力
- 既に入力されていた敵の速度についてはスペックシートの数値の1/2の速度を入力（移動速度が速すぎるのを何とかしてくれと言われた件について、詳細はまた決めてほしい）
- NonIngameManagerモードにおいて指定した敵以外がスポーンする問題の修正。
動作確認用シーン：InGame_EnemyTest
- [] 命名規則の統一
> 抜けていた移動速度の情報を修正

- Assets/Plugins/Adventure_Character/Animation/Dying.fbx.meta
- Assets/Plugins/Adventure_Character/Animation/Player.controller
- Assets/Plugins/Adventure_Character/Animation/Standing Up .fbx.meta
- Assets/Scenes/InGame_Player.unity
- Assets/Scripts/Scenes/InGame/Player/PlayerSpawn/PlayerSpawner.cs
- Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
- Assets/Scripts/Scenes/InGame/Player/TempPlayerMove.cs
- Assets/Scripts/Scenes/InGame/System/UI/FadeBlackImage.cs
死亡時や蘇生時の処理の修正を行った
- 当たり判定の変更を改善。よりアニメーションに沿って変わるようになった。
- 蘇生時に暗転してた画面を解除できるようにした。
- 蘇生アニメーション中は動けないようにした
動作確認用シーン：InGame_Player
- 現在別ブランチにてPlayerUIを触っているので、確かめる際はお手数ですがPlayerUIにFadeOut_InCanvasを追加してから試してほしいです。
> 死亡・蘇生時の処理の修正

- Assets/Scenes/APIDevelop.unity
- Assets/Scripts/Data/APITester.cs
- Assets/Scripts/Data/APITester.cs.meta
- Assets/Scripts/Data/EnemyDataStruct.cs
- Assets/Scripts/Data/PlayerDataStruct.cs
- Assets/Scripts/Data/SpellStruct.cs
- Assets/Scripts/Data/SpellStruct.cs.meta
- Assets/Scripts/Data/WebDataRequest.cs
MySQLのデータを取得するAPIの作成
- Test用のシーンの編集(APIdevelop)
- PHP経由でMySQLでのデータを取得する機能実装
動作確認用シーン：APIdevelop
API確認シーンで各種ボタンを押すと、MySQLのデータを確認できます
- [] 命名規則の統一
> MySQLのデータを取得するAPIの作成

- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
https://github.com/InnovaGameCreate/mythos-encounter/issues/151
https://github.com/InnovaGameCreate/mythos-encounter/issues/150
上記２つのissueの解決
- StageReadyの関数を発行する位置を修正
動作確認用シーン：
- [] 命名規則の統一
> StageReadyが２回呼ばれる問題を修正

- Assets/Scripts/Scenes/InGame/Stage/StageLight.cs
スイッチのアニメーションを追加
StageLightにコードを追加
動作確認用シーン：InGame_Stage_LightTest
> スイッチのアニメーション機能

- Assets/Scripts/Scenes/InGame/Enemy/EnemyAttack.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyMove.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemySearch.cs
- Assets/Scripts/Scenes/InGame/Enemy/MiGoSearch.cs
ドール使用時に敵キャラクターの移動先が変更されるようになった
- ドールが使用されると敵キャラクターが移動し終わった判定になり即座に次の移動先を検索するようになった
> プレイヤーがドールを使用したのちに敵の移動先が変更されるようになった

- Assets/Resources/Prefab/MapCanvas.prefab
MAPの表示順について修正
- Mapの床の線を表示させないようにした
- [] 命名規則の統一
> MAPの表示順について修正

- Packages/manifest.json
- Packages/packages-lock.json
ParrelSyncライブラリを追加した。
Package周りの設定ファイル
動作確認用シーン：
> ParrelSyncライブラリの追加

- Assets/Resources/Prefab/Enemy/EnemySpowner.prefab
- Assets/Scenes/InGame.unity
Ingameシーンの敵のInspectorの情報をプレハブに反映する形で、プレハブとメインシーンのInspectorのデータを一致させた
- IngameシーンのEnemySpawnerのInspectorの情報がPrefabをそのまま参照する形になった
- EnemySpawnerプレハブのInspectorがもともとInGameシーンで設定されていた情報になった
- [] 命名規則の統一
> InGameシーンの敵のInspectorの情報をプレハブに反映する形で、プレハブとメインシーンのInspectorのデータを一致させた

- .gitignore
不必要なファイルをgit.ignoreに追加
- .unitypackage.meta
- Assets\Resources\Texture\Map.renderTexture 
動作確認用シーン：
- [] 命名規則の統一
> 不必要なファイルをgit.ignoreに追加

- Assets/Resources/Prefab/SpellUnlockSystem.prefab
- Assets/Resources/Prefab/SpellUnlockSystem.prefab.meta
- Assets/Scenes/InGame_Player.unity
- Assets/Scripts/Common/Player.meta
- Assets/Scripts/Common/Player/SpellUnlockSystem.cs
- Assets/Scripts/Common/Player/SpellUnlockSystem.cs.meta
- Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/DollEffect.cs
- Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
- Assets/Scripts/Scenes/InGame/System/EscapePoint.cs
呪文解放条件の機能実装しました。
現時点で作れる条件は作りました
- 呪文解放条件の機能実装
- 3,4,5,6,8番目の呪文の解放条件を作成
動作確認用シーン：Ingame_Player
- 仮置きで作成しています。今後別のスクリプトに移植する可能性があります
> 呪文解放条件の機能実装

- Assets/Scripts/Scenes/InGame/Enemy/EnemyAttack.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyVisibilityMap.cs
- Assets/Scripts/Scenes/InGame/Enemy/UniqueScripts/DeepOnesAction.cs
- Assets/Scripts/Scenes/InGame/Enemy/UniqueScripts/SpawnOfCthulhuAction.cs
深き者どもとクトゥルフの落とし子へ依頼されていた変更をくわえました
- 捜索時に捜索した情報を共有するようになりました（同じ場所を仲良く移動することはなくなりました、これからは手分けして屋敷中を探します）
- 増援として呼ばれた深き者どもは増援を呼ぶ能力を持ちません
- 増援として呼ばれた深き者どもは遠隔攻撃ができません
> 深き者どもとクトゥルフの落とし子の仲間を呼ぶ能力に変更をくわえました

- Assets/Resources/Prefab/Item/Doll.prefab
VooDo人形にモデルを変更
- VooDo人形にモデルを変更
動作確認用シーン：
- [] 命名規則の統一
> VooDo人形にモデルを変更

- Assets/Resources/Prefab/Enemy/DeepOnes.prefab
- Assets/Resources/Prefab/Enemy/MiGo.prefab
- Assets/Resources/Prefab/Enemy/SpawnOfCthulhu.prefab
- Assets/Resources/Prefab/Enemy/TestEnemy.prefab
- Assets/Scripts/Scenes/InGame/Enemy/Animation/SpawnOfCthulhuAnim.cs
- Assets/Scripts/Scenes/InGame/Enemy/Animation/TestEnemyAnim.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyAttack.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyMove.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemySearch.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemySpawner.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyStatus.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyVisibilityMap.cs
- Assets/Scripts/Scenes/InGame/Enemy/MiGoSearch.cs
- Assets/Scripts/Scenes/InGame/Enemy/UniqueScripts/DeepOnesAction.cs
- Assets/Scripts/Scenes/InGame/Enemy/UniqueScripts/SpawnOfCthulhuAction.cs
- Assets/Scripts/Scenes/InGame/Player/Magic/MagicScripts/BindMagic.cs
- Assets/Scripts/Scenes/InGame/Player/Magic/MagicScripts/GenerateWaterMagic.cs
大規模なリファクタリングです
- 敵のスペック情報はすべてEnemyStatusに集約されました
- 敵の情報のうちいくつものスクリプトをまたいでいる/またぐ予定のものをEnemyStatusに集約しました。speedなどがそれにあたります
- 仕様から消えた変数をいスクリプトの中にハードコード（視界の長さ）
- 未使用になっていた変数を削除
- 未使用になっていた関数を削除
- 変数名の間違いを削除
- デバッグ時にマップ上に書き込まれる光が実際に届く距離を無視して無限に届くものとして描画されていたのを修正
- プレハブが一部壊れているのを修正
- Bindのデバフと水のデバフが同時に食らったとき、一時的に（1s以下）片方のデバフしか反映されないことを修正
- スタミナ切れデバフ硬直、Stateの変更による速度変化が1s待つことなくすぐに反映されるように修正（副次的にプレイヤーに体をこすりつけなくなった）
動作確認用シーン：Ingame_Enemy Test
- MiGoのプレハブが壊れている、enemy/raffleブランチにて修正してます
> Enemy関連のリファクタリング

- Assets/Photon/Fusion/Resources/NetworkProjectConfig.fusion
- Assets/Scripts/HostMigration.meta
- Assets/Scripts/HostMigration/HostMigrationHandler.cs
- Assets/Scripts/HostMigration/HostMigrationHandler.cs.meta
- Assets/Scripts/HostMigration/HostMigrationObservable.cs
- Assets/Scripts/HostMigration/HostMigrationObservable.cs.meta
- Assets/Scripts/HostMigration/HostMigrationObserver.cs
- Assets/Scripts/HostMigration/HostMigrationObserver.cs.meta
- Assets/Scripts/HostMigration/Test.meta
- Assets/Scripts/HostMigration/Test/InGame.unity
- Assets/Scripts/HostMigration/Test/InGame.unity.meta
- Assets/Scripts/HostMigration/Test/Player.prefab
- Assets/Scripts/HostMigration/Test/Player.prefab.meta
- Assets/Scripts/HostMigration/Test/PlayerInfo.cs
- Assets/Scripts/HostMigration/Test/PlayerInfo.cs.meta
- Assets/Scripts/HostMigration/Test/Runner.prefab
- Assets/Scripts/HostMigration/Test/Runner.prefab.meta
- Assets/Scripts/HostMigration/Test/RunnerManager.cs
- Assets/Scripts/HostMigration/Test/RunnerManager.cs.meta
- Assets/Scripts/HostMigration/Test/Start.unity
- Assets/Scripts/HostMigration/Test/Start.unity.meta
- Assets/Scripts/HostMigration/Test/StartManager.cs
- Assets/Scripts/HostMigration/Test/StartManager.cs.meta
ホスト遷移を行うスクリプトを追加しました。
1. Assets/Photon/Fusion/Resources/NetworkProjectConfig/HostMigration/EnableAutoUpdateをチェックの変更
2. Assets/Scripts/HostMigrationの追加
フォルダ：Assets/Scripts/Test
動作確認用シーン：Start, InGame
テスト手順
1. BuildSettingのSceneInBuildの1番目にInGameシーンを入れる。
2. Startシーンでボタンを押す。
InGameシーンでホストを切断すると、クライアントがホストに切り替わるはずです。
> ホスト遷移の実装（完成版）

- Assets/Scripts/Scenes/InGame/Enemy/EnemyAttack.cs
EnemyAtackにメソッドが二重に存在したのを修正
- EnemyAtackにメソッドが二重に存在したのを修正
動作確認用シーン：Ingame_Enemy Test
- [] 命名規則の統一
> EnemyAtackにメソッドが二重に存在したのを修正

- Assets/Scripts/Scenes/InGame/Player/PlayerMove.cs
RobbyでのUI操作のときなど、手軽に回転を禁止できるようにする
- 概要の通り
動作確認用シーン：
- hotfixなのでレビューなしでマージします。変更箇所ほぼないので後で問題は起きないと思います
> 回転を禁止にする専用のboolを作成

- Assets/Resources/Prefab/API.meta
- Assets/Resources/Prefab/API/APIManager.prefab
- Assets/Resources/Prefab/API/APIManager.prefab.meta
- Assets/Resources/Prefab/API/APITest.prefab
- Assets/Resources/Prefab/API/APITest.prefab.meta
- Assets/Resources/Prefab/API/PlayerInformation.prefab
- Assets/Resources/Prefab/API/PlayerInformation.prefab.meta
- Assets/Scenes/APIDevelop.unity
- Assets/Scripts/Data/APITester.cs
- Assets/Scripts/Data/EnemyAttackStruct.cs
- Assets/Scripts/Data/EnemyAttackStruct.cs.meta
- Assets/Scripts/Data/EnemyDataStruct.cs
- Assets/Scripts/Data/WebDataRequest.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyAttack.cs
データベース上の敵のパラメータに痕跡と攻撃方法の情報の追加
攻撃方法のテーブルの追加
- 攻撃方法のテーブルを取得するクエリの作成
- 敵情報を取得するクエリの更新
- テスト用の環境更新
動作確認用シーン：APIDevelop
確認事項は以下３点
1.シーン再生時にエラーが発生しない
2.EnemyTableのボタンを押すと、項目が以下の通り
id,name,hp,stamia,armor,walkSpeed,dashSpeed,attack,actionCoolTime,sapell,san,feature,attackMethod
3.EnemyAttackのボタンを押すと、項目が以下の通りになっており、9体分の敵の攻撃のパラメータが表示される
id,name,d_damage,b_damage,stanTime,probability,accuracy,speed
> [APIの更新]敵の情報追加

- Assets/Scripts/Scenes/InGame/Multi/Player/MultiPlayerMove.cs
ChangeStaminaでエラーが出ていたので修正
- ChangeStaminaの引数をStringからChangeValueModeに変更
動作確認用シーン：
- [] 命名規則の統一
> safemodeに入るエラーの修正

- Assets/Scenes/APIDevelop.unity
- Assets/Scripts/Data/APITester.cs
- Assets/Scripts/Data/PlayerInformation.cs
- Assets/Scripts/Data/PlayerInformationFacade.cs
プレイヤーの情報をPlayerInformationを元に更新できるように修正
- PlayerInformationFacadeの機能追加
- PlayerInformationFacadeの文字化けしたコメントアウトの修正
- IngameにAPIのprefabの追加
動作確認用シーン：
特に動作確認できる場所はございません
- [] 命名規則の統一
> プレイヤーの情報をPlayerInformationを元に更新できるように修正

- Assets/Editor/DebugMenu.cs
- Assets/Editor/DebugMenu.cs.meta
- Assets/Scripts/Scenes/InGame/Player/PlayerStatus.cs
デバッグ用のツール開発
- デバッグ用のツールを作成しました。以下にできることを列挙
1. 脱出地点にワープ
2. 脱出アイテムを全て目の前に移動
3. プレイヤーの体力, SAN値をSliderで変更可能
4. 敵の攻撃を無効化
5. アイテムの生成(asset/Resources/Prefab/Itemの中にPrefabファイルを置くと自動でボタンが増えます)
6. 生成するアイテムの検索
動作確認用シーン：Ingame_Player or Ingame
メニューバーのところに「DebugTool」項目が増えているので、そこを押してCreateGUIを選択してください。
レイアウトとしては以下の写真のように想定しています。
- オンライン環境には未対応です
- プレイヤーが出てこないシーンでは使えないです。
> デバッグ用のツール開発

- Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
EnemyStatusでStateの変数名が変更されて参照のエラーが出ていたため修正
動作確認用シーン：
- [] 命名規則の統一
> featureviewの修正

- Assets/Scripts/Scenes/InGame/Player/Item/PlayerItem.cs
サブスクライブ先を変更
動作確認用シーン：
- [] 命名規則の統一
> playeritemのエラーの修正

- Assets/Resources/Prefab/Manager.prefab
- Assets/Resources/Prefab/Manager.prefab.meta
InGameManagerにNetworkObjectスクリプトを追加した
- InGameManagerオブジェクトにNetworkOnjectをアタッチ
- InGameManager.csをMonoBehaviourからNetworkBehaviourに変更
動作確認用シーン：なし
- [] 命名規則の統一
> InGameManagerをネットワークオブジェクトにしました

- Assets/Scenes/InGame_EnemyTest.unity
シーンが壊れてるの直した
動作確認用シーン：
- [] 命名規則の統一
> EnemyTestシーンを修正

- Assets/Scenes/InGame.unity
なんかうまくいくって橋本言ってた
いいかんじのなにか
動作確認用シーン：いんげーむかな？
- [] 命名規則の統一
多分大丈夫？
> Ingameに必要なprefabの追加

- Assets/Resources/Prefab/Stage.prefab
- Assets/Resources/Prefab/Stage/HorrorHouse/JournalRoom_HH.prefab
- Assets/Scripts/Scenes/InGame/Stage/StageGenerator.cs
- Assets/Scripts/Scenes/InGame/Stage/StagePrefabPool.cs
- Assets/Scripts/Scenes/InGame/System/JournalItem.cs
ジャーナルロームがステージに生成されるように修正
動作確認用シーン：
- [] 命名規則の統一
> ジャーナルロームがステージに生成されるように修正

- Assets/Scenes/InGame.unity
> ジャーナル用のキャンバスの追加

- Assets/Resources/Prefab/Item/TrapFood/UsingTrapFood.prefab
- Assets/Scripts/Scenes/InGame/Enemy/EnemyMove.cs
- Assets/Scripts/Scenes/InGame/Enemy/EnemyStatus.cs
- Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/AppetitteFeature.cs
- Assets/Scripts/Scenes/InGame/Enemy/Trace/Feature/FeatureView.cs
- Assets/Scripts/Scenes/InGame/Enemy/Trace/TraceFeatureController.cs
- Assets/Scripts/Scenes/InGame/Player/Item/TrapFood/TrapFoodSensor.cs
とらっぷふーどがうごくよやったね
- トラップフード敵呼び寄せる
- 敵トラップフード食べる
- 敵がトラップフード食べるかどうか最初に決定できる
- 敵がトラップフードを食べるかどうかを決定するのに敵の種類を参照できる
動作確認用シーン：
- [] 命名規則の統一
- スクリプトまじきたねぇ
> Testplay/2nd time/trapfood object and enemy appetite

- Assets/Resources/Prefab/Stage/ItemGenerator.prefab
ItemGeneraterにアイテムを設定
- ItemGeneraterにアイテムを設定
動作確認用シーン：
- [] 命名規則の統一
- テストプレイしていない
> ItemGeneraterにアイテムを設定

- Assets/Scripts/Scenes/InGame/Player/Item/ItemEffectScript/AdrenalineSyringeEffect.cs
> アドレナリンのバグを修正した

- Assets/Plugins/ModularCreepyAbandonedHospital/Materials/props5.mat
- Assets/Resources/Prefab/Item/Compass.prefab
- Assets/Resources/Prefab/Item/GeigerCounter.prefab
- Assets/Resources/Prefab/Item/SanityPotion.prefab
- Assets/Resources/Prefab/Item/Thermometer.prefab
- Assets/Resources/Prefab/Item/UsingItem/Compass/UsingCompass.prefab
- Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/GeigerCounter/GeigerCounterMove.cs
- Assets/Scripts/Scenes/InGame/Player/Item/UsingItem/Thermometer/ThermometerMove.cs
アイテムプレハブの差し替え
- コンパス
- 放射線測定器
- SAN値回復役
- 温度計
> アイテムプレハブの差し替え

- Assets/Resources/Prefab/Enemy/Feature/Scrach.prefab
- Assets/Resources/Prefab/Enemy/Feature/Scrach.prefab.meta
- Assets/Resources/Prefab/Enemy/Feature/ScratchSprite.prefab
- Assets/Resources/Prefab/Enemy/TraceFeatureManager.prefab
Inspacterが設定されていない状態を修正
- [] 命名規則の統一
> Inspacterが設定されていない状態を修正

- Assets/Resources/Prefab/Enemy/DeepOnes.prefab
- Assets/Resources/Prefab/Enemy/MiGo.prefab
- Assets/Resources/Prefab/Enemy/SpawnOfCthulhu.prefab
- Assets/Scripts/Scenes/InGame/Multi/Player/MultiPlayerMove.cs
試遊会のフィードバックを元に、キャラクターの移動速度を調整しました。
- マルチプレイキャラクターの調整
- 1段階目の敵のキャラクターの調整
動作確認用シーン：
> キャラクターの移動速度の修正
